spring:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: user
    password: password
    driver-class-name: org.postgresql.Driver